export const receivable =
    `
<ENVELOPE>
<HEADER>
<TALLYREQUEST>Export Data</TALLYREQUEST>
</HEADER>
<BODY>
<EXPORTDATA>
<REQUESTDESC>
<STATICVARIABLES>
<SVFROMDATE>20240401</SVFROMDATE>
<SVTODATE>20250331</SVTODATE>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
</STATICVARIABLES>
<REPORTNAME>Rpt_TNX_ExpOutstandings</REPORTNAME>
</REQUESTDESC>
</EXPORTDATA>
</BODY>
</ENVELOPE>
 `


export const ledger =
`
 <ENVELOPE>
<HEADER>
<TALLYREQUEST>Export Data</TALLYREQUEST>
</HEADER>
<BODY>
<EXPORTDATA>
<REQUESTDESC>
<STATICVARIABLES>
<SVFROMDATE>20240401</SVFROMDATE>
<SVTODATE>20250331</SVTODATE>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<DBBILLEXPLODEFLAG>YES</DBBILLEXPLODEFLAG>
<EXPLODEVNUM>YES</EXPLODEVNUM>
<SHOWRUNBALANCE>Yes</SHOWRUNBALANCE>
</STATICVARIABLES>
<REPORTNAME>Rpt_TNX_ExpLedStat</REPORTNAME>
</REQUESTDESC>
</EXPORTDATA>
</BODY>
</ENVELOPE>
`